name: geospatial
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - affine=2.3.0=pyhd3eb1b0_0
  - alsa-lib=1.2.6.1=h7f98852_0
  - aom=3.3.0=h27087fc_1
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310h7f8727e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attr=2.5.1=h166bdaf_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py310h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.1=h83bc5f7_3
  - boost-cpp=1.74.0=h75c5d50_8
  - bottleneck=1.3.5=py310ha9d4c09_0
  - branca=0.5.0=pyhd8ed1ab_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py310h7f8727e_1002
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - c-blosc2=2.2.0=h7a311fb_0
  - ca-certificates=2022.07.19=h06a4308_0
  - cairo=1.16.0=ha61ee94_1011
  - certifi=2022.6.15=py310h06a4308_0
  - cffi=1.15.0=py310hd667e15_1
  - cfitsio=4.1.0=hd9d235c_0
  - charls=2.3.4=h9c3ff4c_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py310h06a4308_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=pyhd3eb1b0_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - cryptography=37.0.1=py310h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - curl=7.83.1=h7bff187_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.11.0=py310h7f8727e_0
  - dask-core=2022.5.0=py310h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py310h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.8=h27087fc_0
  - ffmpeg=4.4.2=habc3f16_0
  - fftw=3.3.10=nompi_h77c792f_102
  - fiona=1.8.21=py310h60a68a4_2
  - folium=0.12.1.post1=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.11.0=h70c0345_0
  - freexl=1.0.6=h27cfd23_0
  - fsspec=2022.3.0=py310h06a4308_0
  - geopandas=0.11.0=pyhd8ed1ab_0
  - geopandas-base=0.11.0=pyha770c72_0
  - geos=3.10.3=h27087fc_0
  - geotiff=1.7.1=h4fc65e6_2
  - gettext=0.21.0=hf68c758_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.70.2=h780b84a_4
  - glib-tools=2.70.2=h780b84a_4
  - gmp=6.2.1=h295c915_3
  - gnutls=3.7.6=hb5d6004_1
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.20.3=hf6a322e_0
  - gstreamer=1.20.3=hd4edc92_0
  - harfbuzz=4.4.1=hf9f4e7c_0
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.12.1=nompi_h2386368_104
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd3eb1b0_0
  - imagecodecs=2022.2.22=py310h3ac3b6e_6
  - imageio=2.9.0=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.9.1=py310h06a4308_0
  - ipython=8.3.0=py310h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jack=1.9.18=h8c3723f_1002
  - jasper=2.0.33=ha77e612_0
  - jedi=0.18.1=py310h06a4308_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - json-c=0.16=hc379101_0
  - jsonschema=4.4.0=py310h06a4308_0
  - jupyter=1.0.0=py310hff52083_7
  - jupyter_client=7.2.2=py310h06a4308_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.10.0=py310h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - jxrlib=1.1=h7b6447c_2
  - kealib=1.4.15=hfe1a663_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.2=py310h295c915_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.6=h9c3ff4c_0
  - libavif=0.10.1=h166bdaf_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcap=2.64=ha37c62d_0
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=14.0.6=default_h2e3cab8_0
  - libclang13=14.0.6=default_h3a83d3e_0
  - libcups=2.3.3=hf5a7f15_1
  - libcurl=7.83.1=h7bff187_0
  - libdap4=3.20.6=hd7c4107_2
  - libdb=6.2.32=h6a678d5_1
  - libdeflate=1.12=h166bdaf_0
  - libdrm=2.4.111=h166bdaf_0
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h295c915_4
  - libflac=1.3.4=h27087fc_0
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgdal=3.5.0=hc0ebe42_4
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.70.2=h174f98d_4
  - libglu=9.0.0=hf484d3e_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libkml=1.3.0=h238a007_1014
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm14=14.0.6=he0ac6c6_0
  - libnetcdf=4.8.1=nompi_h329d8a1_102
  - libnghttp2=1.47.0=h727a467_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.5=h27cfd23_1
  - libopencv=4.5.5=py310hcb97b83_12
  - libopus=1.3.1=h7b6447c_0
  - libpciaccess=0.16=h516909a_0
  - libpng=1.6.37=hbc83047_0
  - libpq=14.4=hd77ab85_0
  - libprotobuf=3.20.1=h4ff587b_0
  - librttopo=1.1.0=h40fdbc5_10
  - libsndfile=1.0.31=h9c3ff4c_1
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=h2531618_0
  - libspatialite=5.0.1=hc16130b_17
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.4.0=hc85c160_1
  - libtool=2.4.6=h295c915_1008
  - libudev1=249=h166bdaf_4
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7b6447c_0
  - libva=2.15.0=h166bdaf_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.11.0=h295c915_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.14=h22db469_0
  - libzip=1.8.0=h5cef20c_0
  - libzlib=1.2.12=h166bdaf_1
  - libzopfli=1.0.3=he6710b0_0
  - llvm-openmp=14.0.4=he0ac6c6_0
  - locket=1.0.0=py310h06a4308_0
  - lz4-c=1.9.3=h295c915_1
  - mapclassify=2.4.3=pyhd3eb1b0_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - matplotlib-base=3.5.1=py310ha18d171_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py310h7f8727e_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - munch=2.5.0=pyhd3eb1b0_0
  - munkres=1.1.4=py_0
  - mysql-common=8.0.29=haf5c9bc_1
  - mysql-libs=8.0.29=h28c427c_1
  - nbclient=0.5.13=py310h06a4308_0
  - nbconvert=6.4.4=py310h06a4308_0
  - nbformat=5.3.0=py310h06a4308_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.5=py310h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.7.1=pyhd3eb1b0_0
  - notebook=6.4.11=py310h06a4308_0
  - nspr=4.33=h295c915_0
  - nss=3.78=h2350873_0
  - numexpr=2.8.3=py310hcea2de6_0
  - numpy=1.22.3=py310hfa59a62_0
  - numpy-base=1.22.3=py310h9585f30_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1q=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.2=py310h295c915_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py310h22f2fdc_0
  - pip=21.2.4=py310h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - poppler=22.04.0=h1434ded_1
  - poppler-data=0.4.11=h06a4308_0
  - portaudio=19.6.0=h7b6447c_4
  - postgresql=14.4=hfdbbde3_0
  - proj=9.0.1=h93bde94_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pulseaudio=14.0=h7f54b18_8
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-opencv=4.5.5=py310hfdc917e_12
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyproj=3.3.1=py310hf94497c_1
  - pyqt=5.15.4=py310h29803b5_1
  - pyrsistent=0.18.0=py310h7f8727e_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.5=h582c2e5_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=1.11.0=py3.10_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=py310h06a4308_0
  - pywavelets=1.3.0=py310h7f8727e_0
  - pyzmq=22.3.0=py310h295c915_2
  - qt-main=5.15.4=ha5833f6_2
  - qtconsole=5.3.0=pyhd3eb1b0_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - rasterio=1.2.10=py310h1bedc6d_7
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.0=py310h06a4308_0
  - rtree=0.9.7=py310h06a4308_1
  - scikit-image=0.19.2=py310h00e6091_0
  - scikit-learn=1.1.1=py310hffb9edd_0
  - scipy=1.8.1=py310h7612f91_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=61.2.0=py310h06a4308_0
  - shapely=1.8.2=py310h7b2ee30_2
  - sip=6.5.1=py310h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h295c915_0
  - snuggs=1.4.7=pyhd3eb1b0_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.38.5=hc218d9a_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - svt-av1=1.1.0=h27087fc_1
  - terminado=0.13.1=py310h06a4308_0
  - testpath=0.6.0=py310h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tiledb=2.9.5=h1e4a385_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchaudio=0.11.0=py310_cu113
  - torchmetrics=0.9.2=pyhd8ed1ab_0
  - torchvision=0.12.0=py310_cu113
  - tornado=6.1=py310h7f8727e_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzcode=2022a=h166bdaf_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.9=py310h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310h06a4308_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py310h06a4308_0
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xerces-c=3.2.3=h55805fa_5
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xyzservices=2022.6.0=pyhd8ed1ab_0
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zfp=0.5.5=h295c915_6
  - zlib=1.2.12=h166bdaf_1
  - zlib-ng=2.0.6=h166bdaf_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - albumentations==1.2.1
    - gdal==3.5.0
    - opencv-python-headless==4.6.0.66
    - pyqt5-sip==12.9.0
    - pyyaml==6.0
    - qudida==0.0.4
prefix: /home/sl636/miniconda3/envs/geospatial
